#!/usr/bin/env bash
# DataPIM — configure external proxy VPS (nginx + SSL).
#
# Run on the proxy VPS that already has nginx installed.
# This script generates a server block and issues a Let's Encrypt cert.
#
# Usage:
#   sudo bash proxy-setup.sh
#   # → prompts for DOMAIN, BACKEND_URL, EMAIL

set -euo pipefail

log()  { printf "\033[1;36m▶\033[0m %s\n" "$*"; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
err()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; }

# --- 1. Collect inputs ------------------------------------------------------
read -rp "Домен (напр. datapim.example.com): " DOMAIN
read -rp "URL внутрішнього сервера (напр. http://192.168.1.100:3000): " BACKEND_URL
read -rp "Email для Let's Encrypt: " CERT_EMAIL

[[ -z "$DOMAIN" || -z "$BACKEND_URL" || -z "$CERT_EMAIL" ]] && { err "All fields required"; exit 1; }

CONF_PATH="/etc/nginx/sites-enabled/datapim.conf"

# --- 2. Generate nginx config -----------------------------------------------
log "Writing $CONF_PATH"

cat > "$CONF_PATH" <<NGINX
# DataPIM reverse proxy — auto-generated by proxy-setup.sh
# Domain: $DOMAIN → $BACKEND_URL

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache   shared:datapim_ssl:10m;
    ssl_session_timeout 1d;

    # Security headers
    add_header X-Frame-Options           "DENY"               always;
    add_header X-Content-Type-Options    "nosniff"            always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;

    client_max_body_size 12m;

    location / {
        proxy_pass         $BACKEND_URL;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Connection        "";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
NGINX

ok "nginx config written"

# --- 3. Test nginx config ---------------------------------------------------
log "Testing nginx config"
nginx -t || { err "nginx config invalid — check $CONF_PATH"; exit 1; }
ok "nginx -t passed"

# --- 4. Get SSL cert --------------------------------------------------------
CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"
if [[ -f "${CERT_DIR}/fullchain.pem" ]]; then
  ok "Cert already exists for $DOMAIN"
else
  log "Issuing Let's Encrypt cert"
  mkdir -p /var/www/certbot
  # Reload nginx first so port 80 serves ACME challenges
  nginx -s reload || systemctl reload nginx || true
  sleep 2
  certbot certonly --webroot -w /var/www/certbot \
    --non-interactive --agree-tos \
    --email "$CERT_EMAIL" \
    -d "$DOMAIN"
  ok "Cert issued"
fi

# --- 5. Reload nginx with SSL -----------------------------------------------
log "Reloading nginx"
nginx -s reload || systemctl reload nginx
ok "nginx reloaded"

# --- 6. Verify --------------------------------------------------------------
log "Verifying https://${DOMAIN}"
if curl -fsk "https://${DOMAIN}/health" >/dev/null 2>&1; then
  ok "https://${DOMAIN}/health OK"
else
  err "Could not reach https://${DOMAIN}/health"
  err "Check: dig $DOMAIN, internal server running, firewall"
fi

cat <<EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Proxy configured for $DOMAIN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 URL:    https://$DOMAIN/
 Config: $CONF_PATH
 Cert:   $CERT_DIR/

 Auto-renew cron (add once):
   0 3 * * * certbot renew --quiet && nginx -s reload
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
