"""initial schema

Revision ID: c4181ab0126d
Revises:
Create Date: 2026-04-14 19:29:49.501804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4181ab0126d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("product_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index("idx_categories_external_id", "categories", ["external_id"], unique=True)
    op.create_index("idx_categories_is_active", "categories", ["is_active"], unique=False)
    op.create_index("idx_categories_parent_id", "categories", ["parent_id"], unique=False)
    op.create_table(
        "import_logs",
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "completed", "failed", name="import_status"),
            nullable=False,
        ),
        sa.Column("products_created", sa.Integer(), nullable=False),
        sa.Column("products_updated", sa.Integer(), nullable=False),
        sa.Column("products_stock_changed", sa.Integer(), nullable=False),
        sa.Column("categories_upserted", sa.Integer(), nullable=False),
        sa.Column("errors_count", sa.Integer(), nullable=False),
        sa.Column("error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_import_logs_started_at", "import_logs", ["started_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "operator", "manager", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("theme", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    op.create_index("idx_users_is_active", "users", ["is_active"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "products",
        sa.Column("internal_code", sa.String(length=50), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("buf_name", sa.String(length=500), nullable=False),
        sa.Column("custom_name", sa.String(length=500), nullable=True),
        sa.Column("buf_brand", sa.String(length=255), nullable=True),
        sa.Column("custom_brand", sa.String(length=255), nullable=True),
        sa.Column("buf_country", sa.String(length=100), nullable=True),
        sa.Column("custom_country", sa.String(length=100), nullable=True),
        sa.Column("buf_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("buf_currency", sa.String(length=3), nullable=False),
        sa.Column("buf_quantity", sa.Integer(), nullable=True),
        sa.Column("buf_in_stock", sa.Boolean(), nullable=False),
        sa.Column("uktzed", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("seo_title", sa.String(length=255), nullable=True),
        sa.Column("seo_description", sa.Text(), nullable=True),
        sa.Column("has_pending_review", sa.Boolean(), nullable=False),
        sa.Column(
            "enrichment_status",
            sa.Enum("none", "partial", "full", name="enrichment_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("internal_code"),
    )
    op.create_index("idx_products_buf_in_stock", "products", ["buf_in_stock"], unique=False)
    op.create_index("idx_products_category_id", "products", ["category_id"], unique=False)
    op.create_index(
        "idx_products_enrichment_status", "products", ["enrichment_status"], unique=False
    )
    op.create_index(
        "idx_products_has_pending_review", "products", ["has_pending_review"], unique=False
    )
    op.create_index("idx_products_internal_code", "products", ["internal_code"], unique=True)
    op.create_index("idx_products_is_active", "products", ["is_active"], unique=False)
    op.create_table(
        "ai_tasks",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("text", "image", name="ai_task_type"), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "failed", name="ai_task_status"),
            nullable=False,
        ),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ai_tasks_created_at", "ai_tasks", ["created_at"], unique=False)
    op.create_index("idx_ai_tasks_product_id", "ai_tasks", ["product_id"], unique=False)
    op.create_index("idx_ai_tasks_status", "ai_tasks", ["status"], unique=False)
    op.create_index("idx_ai_tasks_type", "ai_tasks", ["type"], unique=False)
    op.create_index("idx_ai_tasks_user_id", "ai_tasks", ["user_id"], unique=False)
    op.create_table(
        "product_attributes",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("source", sa.Enum("manual", "ai", name="attribute_source"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "key", name="uq_product_attributes_product_key"),
    )
    op.create_index(
        "idx_product_attributes_product_id", "product_attributes", ["product_id"], unique=False
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sa.Enum("upload", "ai", "import_", name="image_source"), nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_product_images_product_id", "product_images", ["product_id"], unique=False)
    op.create_table(
        "ai_reviews",
        sa.Column("ai_task_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "partial", name="ai_review_status"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("changes_applied", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["ai_task_id"], ["ai_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ai_task_id"),
    )
    op.create_index("idx_ai_reviews_ai_task_id", "ai_reviews", ["ai_task_id"], unique=True)
    op.create_index("idx_ai_reviews_reviewed_by", "ai_reviews", ["reviewed_by"], unique=False)
    op.create_index("idx_ai_reviews_status", "ai_reviews", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ai_reviews_status", table_name="ai_reviews")
    op.drop_index("idx_ai_reviews_reviewed_by", table_name="ai_reviews")
    op.drop_index("idx_ai_reviews_ai_task_id", table_name="ai_reviews")
    op.drop_table("ai_reviews")
    op.drop_index("idx_product_images_product_id", table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("idx_product_attributes_product_id", table_name="product_attributes")
    op.drop_table("product_attributes")
    op.drop_index("idx_ai_tasks_user_id", table_name="ai_tasks")
    op.drop_index("idx_ai_tasks_type", table_name="ai_tasks")
    op.drop_index("idx_ai_tasks_status", table_name="ai_tasks")
    op.drop_index("idx_ai_tasks_product_id", table_name="ai_tasks")
    op.drop_index("idx_ai_tasks_created_at", table_name="ai_tasks")
    op.drop_table("ai_tasks")
    op.drop_index("idx_products_is_active", table_name="products")
    op.drop_index("idx_products_internal_code", table_name="products")
    op.drop_index("idx_products_has_pending_review", table_name="products")
    op.drop_index("idx_products_enrichment_status", table_name="products")
    op.drop_index("idx_products_category_id", table_name="products")
    op.drop_index("idx_products_buf_in_stock", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_is_active", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_import_logs_started_at", table_name="import_logs")
    op.drop_table("import_logs")
    op.drop_index("idx_categories_parent_id", table_name="categories")
    op.drop_index("idx_categories_is_active", table_name="categories")
    op.drop_index("idx_categories_external_id", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
